spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgrez
    url: jdbc:postgresql://127.0.0.1:5432/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: 'true'
        format_sql: 'true'
    hibernate:
      show-sql: 'true'
      ddl-auto: create
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

redis:
  host: 127.0.0.1
  port: 6379
