spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: my-sql-password
    url: jdbc:mysql://localhost:3306/webserver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: 'true'
        format_sql: 'true'
    hibernate:
      show-sql: 'true'
      ddl-auto: create
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace

redis:
  master:
    host: localhost
    port: 6379
  slaves:
    - host: localhost
      port: 6380