spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgrez
#    For k8s
    url: jdbc:postgresql://postgresql-service:5432/postgres
#    For docker
#    url: jdbc:postgresql://spring-postgres:5432/postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: 'true'
        format_sql: 'true'
    hibernate:
      show-sql: 'true'
      ddl-auto: create
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: trace
