
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: my-sql-password
    url: jdbc:mysql://localhost:3306/webserver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: 'false'
        format_sql: 'true'
    hibernate:
      show-sql: 'false'
      ddl-auto: create-drop
    show-sql: 'false'
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR

hibernate:
  type:
    preferred_uuid_jdbc_type: CHAR

redis:
  master:
    host: localhost
    port: 6379
  slaves:
    - host: localhost
      port: 6380

server:
  error:
    include-message=always: