spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: my-sql-password
    url: jdbc:mysql://localhost:3306/webserver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: 'false'
        format_sql: 'true'
    hibernate:
      show-sql: 'false'
      ddl-auto: create-drop
    show-sql: 'false'
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR

hibernate:
  type:
    preferred_uuid_jdbc_type: CHAR

redis:
  master:
    host: localhost
    port: 6379
  slaves:
    - host: localhost
      port: 6380

server:
  error:
    include-message: always

init:
  users:
    - id: c17881a1-41bc-4b4b-9274-5b3f30e96aee
      username: testuser1
      password: testuser1
      recommenderId: null
      role: ADMIN
    - id: 7e1983a2-96cf-47f5-be91-0b4110f8828a
      username: testuser2
      password: testuser2
      recommenderId: c17881a1-41bc-4b4b-9274-5b3f30e96aee
      role: USER
    - id: 8c8c3a48-1ee5-45a4-9eae-96c65b8a8f1f
      username: testuser3
      password: testuser3
      recommenderId: c17881a1-41bc-4b4b-9274-5b3f30e96aee
      role: USER
    - id: 98abf882-34ce-4300-abe2-54fc64664477
      username: testuser4
      password: testuser4
      recommenderId: 7e1983a2-96cf-47f5-be91-0b4110f8828a
      role: USER
    - id: 795093b0-6268-4934-8a92-06b29139d668
      username: testuser5
      password: testuser5
      recommenderId: 7e1983a2-96cf-47f5-be91-0b4110f8828a
      role: USER
    - id: 1fe7ac24-457e-4c13-9cb6-5e7b4e828295
      username: testuser6
      password: testuser6
      recommenderId: 7e1983a2-96cf-47f5-be91-0b4110f8828a
      role: USER
    - id: d72c6dd9-2786-450f-8914-590015c19ea6
      username: testuser7
      password: testuser7
      recommenderId: 7e1983a2-96cf-47f5-be91-0b4110f8828a
      role: USER


#         1
#      2    3
#  4   5    6   7

