apiVersion: v1
kind: Secret
metadata:
  namespace: dev
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: d2Vic2VydmVy # webserver
  POSTGRES_USER: dXNlcg== # user
  POSTGRES_PASSWORD: eW91ci1wb3N0Z3Jlcy1wYXNzd29yZA== # my-sql-password
