apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spring-rabbitmq
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-rabbitmq
  template:
    metadata:
      labels:
        app: spring-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS