apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  namespace: dev
spec:
  selector:
    app: spring-mailhog
  ports:
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: tcp-mail
    - protocol: TCP
      port: 8025
      targetPort: 8025
      name: ui
  type: ClusterIP
