spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: my-sql-password
    url: jdbc:mysql://spring-mysql-master:3306/webserver

redis:
  mater:
    host: spring-redis-master
    port: 6379
  slaves:
    - host: spring-redis-slave
      port: 6380