version: '3.8'

services:
  spring-postgres:
    image: postgres:16
    container_name: spring-postgres
    environment:
      POSTGRES_PASSWORD: postgrez
    ports:
      - "5432:5432"
    networks:
      - dev

  spring-webserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - type: bind
        source: application.yml
        target: /webserver/application.yml
    container_name: spring-webserver
    ports:
      - "8080:8080"
    networks:
      - dev
    depends_on:
      - spring-postgres

networks:
  dev:
    driver: bridge
