apiVersion: v1
kind: Secret
metadata:
  namespace: dev
  name: spring-webserver-secret
type: Opaque
data:
  application.yml: |
    c3ByaW5nOgogIGRhdGFzb3VyY2U6CiAgICBkcml2ZXItY2xhc3MtbmFtZTogY29tLm15c3FsLmNqLmpkYmMuRHJpdmVyCiAgICB1c2VybmFtZTogdXNlcgogICAgcGFzc3dvcmQ6IG15LXNxbC1wYXNzd29yZAogICAgdXJsOiBqZGJjOm15c3FsOi8vbXlzcWwtc2VydmljZTozMzA2L3dlYnNlcnZlcgpyZWRpczoKICBtYXN0ZXI6CiAgICBob3N0OiByZWRpcy1tYXN0ZXItc2VydmljZQogICAgcG9ydDogNjM3OQogIHNsYXZlczoKICAgIC0gaG9zdDogcmVkaXMtc2xhdmUtc2VydmljZQogICAgICBwb3J0OiA2Mzc5Cg==